### ISSUE TITLE
Is this ever going to be put on npm?

### ISSUE THREAD

**Issue by ghost** [FruitsNVeggies/skyward-rest#10]
Your [README](https://github.com/FruitsNVeggies/skyward-rest/blob/master/README.md) says that we can install the library from the npm repos using `npm install skyward-rest`. Are there plans to put it there? 
For now, I would suggest changing it to 
```sh
npm install https://github.com/FruitsNVeggies/skyward-rest
```

**Comment by Kaelinator** [comment]
Yes, as of 1.0.0
