### ISSUE TITLE
The first line is not working.

### ISSUE THREAD

**Issue by BBQ591** [FruitsNVeggies/skyward-rest#26]
When I try the code
`const skyward=require('skyward-rest')`
, it says this:
![IMG_5763](https://user-images.githubusercontent.com/62854243/193117398-af4015f8-ef0d-4d0d-9d5c-52ba9369da76.PNG)
Do I need to do some git install or something to get this working and installed in the node modules?
Sorry, I am new to React-Native and I am still trying to figure things out.

**Comment by shrey150** [comment]
Hey! Did you run `yarn install` in the root directory where `package.json` is located? That installs all Node.js dependencies.

**Comment by BBQ591** [comment]
Yes, I just did. That error disappeared. There is a new error now, and I dont know why it is there:
<img width="1016" alt="Screen Shot 2022-09-29 at 3 34 32 PM" src="https://user-images.githubusercontent.com/62854243/193125587-090675ea-ce35-4326-98c4-7dd0a9ab783e.png">

**Comment by BBQ591** [comment]
To clarify what I've done, this is my current code:
<img width="679" alt="Screen Shot 2022-09-29 at 3 21 02 PM" src="https://user-images.githubusercontent.com/62854243/193123332-fcf4c53b-6019-48df-b0ec-f178635a9b8a.png">
I have also run `npm install skyward-rest`. It cleared up the first issue. However this next issue appeared and I'm not sure what to do

**Comment by BBQ591** [comment]
To clarify what I've done, here is my code:
<img width="661" alt="Screen Shot 2022-09-29 at 3 23 29 PM" src="https://user-images.githubusercontent.com/62854243/193123765-34d2911c-6317-4c91-a29e-22eebc4580b3.png">
I ran `npm install skyward-rest` to get rid of the first error, but I don't know what to do about the second error.

**Comment by BBQ591** [comment]
Also, I believe that my URL is currently redirecting. What should I do to prevent that?

**Comment by shrey150** [comment]
Looking at [this line](https://github.com/Kaelinator/skyward-rest/blob/master/src/reportcard/condense.js#L1), I'm guessing it's because you don't have `cheerio` installed. That should've been installed when you ran `npm install skyward-rest`, but you could manually install using `npm install cheerio`. I would try `yarn install` again and make sure you're doing it in the root directory of your project, which should take care of all peer dependencies. You could also try using [install-peerdeps](https://www.npmjs.com/package/install-peerdeps).

**Comment by BBQ591** [comment]
It still isn't working. Here is the terminal error:
<img width="829" alt="Screen Shot 2022-09-29 at 4 06 28 PM" src="https://user-images.githubusercontent.com/62854243/193131572-04f30514-67d9-4477-b502-cd4e5fc21f28.png">
There is also a pop up on `const skyward=require('skyward-rest')`.
<img width="1299" alt="Screen Shot 2022-09-29 at 4 08 19 PM" src="https://user-images.githubusercontent.com/62854243/193131752-969c2ba7-9ef1-4cdd-bf23-c3f59518022a.png">
I have also tried npm install (I am using npm instead of yarn, so instead of doing yarn install, I am doing npm install). I have done `npm install cheerio` and `npm install skyward-rest`. This is still the error, and I can't seem to find a solution. Thanks a lot for helping me by the way, @shrey150 .

**Comment by BBQ591** [comment]
Actually, never mind, I got it working. However, a new problem has appeared. How do I get the scrapeHistory to display the course 5-digit number? For the scrapeGradebook, it is required, so I assume that it is stored somewhere, but it just isn't being displayed in the scrapeHistory function. How can I access this?
