### ISSUE TITLE
Any plans for future development?

### ISSUE THREAD

**Issue by PotatoCurry** [FruitsNVeggies/skyward-rest#8]
Just wanted to know if there are any plans for continuing this project or plans to port it to other languages.

**Comment by PotatoCurry** [comment]
I'd also like to take this time to say thanks for developing this API, as it's been of immeasurable help in my own projects. :)

**Comment by Kaelinator** [comment]
As of right now, the development has been halted. I'm not too sure if I will ever pick back up on this project, however. If there is enough demand for the features I had in mind, then I will continue.
I appreciate your kind words!

**Comment by Kaelinator** [comment]
I lied, haha, I think I'll finish up with #4 and then throw the towel in!

**Comment by Kaelinator** [comment]
Quick update: development will proceed!
